title: ğŸ±
author:
  name: Jovan Sardinha

minima:
  # (further reference)[https://shopify.github.io/liquid/filters/date/]
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: JovanSardinha
    github:  jovsa
    linkedin: JovanSardinha
    medium: jovansardinha
    email: jovan.sardinha@gmail.com

google_analytics: UA-167534363-1

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag